baseurl = "/"
DefaultContentLanguage = "fi"
languageCode = "fi"
languageLang = "fi"
title = "Vuokrattava studio Empire Tampere"
summaryLength = 30
googleAnalytics = "'UA-178919018-1"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[privacy]
   [privacy.googleAnalytics]
     anonymizeIP = true
     disable = false
     respectDoNotTrack = true
     useSessionStorage = true

[languages]
    [languages.en]
        contentDir = "content/english"
        languagename = "English"
        title = "Rent an Empire"

        [languages.en.menu]
            [[languages.en.menu.nav]]
                identifier = "palvelut"
                name = "Services"
                url = "/en/palvelut"
                weight = 1
            [[languages.en.menu.nav]]
                identifier = "laitteet-ja-kalusto"
                name = "Equipment"
                url = "/en/laitteet-ja-kalusto"
                weight = 2
            [[languages.en.menu.nav]]
                identifier = "yhteystiedot"
                name = "Contact"
                url = "/en/yhteystiedot"
                weight = 3
            [[languages.en.menu.nav]]
                identifier = "blogi"
                name = "Blog"
                url = "/en/blogi"
                weight = 4
            [[languages.en.menu.nav]]
                identifier = "hinnasto"
                name = "Pricing"
                url = "/en/hinnasto"
                weight = 5

    [languages.fi]
        contentDir = "content/finnish"
        languagename = "Suomi"

        [languages.fi.menu]
            [[languages.fi.menu.nav]]
                identifier = "palvelut"
                name = "Palvelut"
                url = "/palvelut"
                weight = 2
                hasChildren = true
            [[languages.fi.menu.nav]]
                identifier = "palvelut-vuokrastudio"
                name = "Vuokrastudio"
                url = "/palvelut/vuokrastudio"
                weight = 1
                parent = "palvelut"
            [[languages.fi.menu.nav]]
                identifier = "palvelut-valityspalvelu"
                name = "Kuvaajien välityspalvelu"
                url = "/palvelut/kuvaajien-valityspalvelu"
                weight = 2
                parent = "palvelut"
            [[languages.fi.menu.nav]]
                identifier = "palvelut-podcastit-ja-aani"
                name = "Podcastit ja ääni"
                url = "/palvelut/podcastit-ja-aani"
                weight = 3
                parent = "palvelut"
            [[languages.fi.menu.nav]]
                identifier = "palvelut-verkkokurssit"
                name = "Verkkokurssit"
                url = "/palvelut/verkkokurssit"
                weight = 4
                parent = "palvelut"
            [[languages.fi.menu.nav]]
                identifier = "palvelut-workshopit"
                name = "Workshopit"
                url = "/palvelut/workshopit"
                weight = 5
                parent = "palvelut"
            [[languages.fi.menu.nav]]
                identifier = "laitteet-ja-kalusto"
                name = "Laitteet ja kalusto"
                url = "/laitteet-ja-kalusto"
                weight = 3
            [[languages.fi.menu.nav]]
                identifier = "yhteystiedot"
                name = "Yhteystiedot"
                url = "/yhteystiedot"
                weight = 4
            [[languages.fi.menu.nav]]
                identifier = "blogi"
                name = "Blogi"
                url = "/blogi"
                weight = 5
            [[languages.fi.menu.nav]]
                identifier = "hinnasto"
                name = "Hinnasto"
                url = "/hinnasto"
                weight = 6
