backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
publish_mode: editorial_workflow
# This line should *not* be indented
media_folder: "site/content/finnish/uploads" # Media files will be stored in the repo under images
public_folder: "uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://vuokrattavastudio.com
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - label: "Front page"
    name: "index"
    files:
      - label: "FI Front page"
        name: "fi-index"
        file: "site/content/finnish/_index.md"
        fields: # The fields for each document, usually in front matter
          - {label: "Title (meta)", name: "title", widget: "string"}
          - {label: "Description (meta)", name: "description", widget: "string"}
          - {label: "Banner", name: "background", widget: "image"}
          - {label: "Banner alt text", name: "alt", widget: "string"}
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Events", name: events, widget: list, fields: [
              {label: "Date", name: "date", widget: "date"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "markdown"}]}
      - label: "EN Front page"
        name: "en-index"
        file: "site/content/english/_index.md"
        fields: # The fields for each document, usually in front matter
          - {label: "Title (meta)", name: "title", widget: "string"}
          - {label: "Description (meta)", name: "description", widget: "string"}
          - {label: "Banner", name: "background", widget: "image"}
          - {label: "Banner alt text", name: "alt", widget: "string"}
          - {label: "Headline", name: "headline", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Events", name: events, widget: list, fields: [
              {label: "Date", name: "date", widget: "date"},
              {label: "Title", name: "title", widget: "string"},
              {label: "Description", name: "description", widget: "markdown"}]}
